### ISSUE TITLE
Clearing of a SID from the RDL

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw#101]
The progress action of TC(3,3) is supposed to clear one or more SIDs from the RDL. This action is implemented in function CrPsHkDeleteCmdProgressAction. Here, I can see that the clearing of a SID from the RDL is implemented by setting to zero all fields of the RDL corresponding to that SID. This is inefficient. Would it not be enough to clear, for instance, the SID attribute of the RDL entry corresponding to the SID to be removed?

**Comment by reimers** [comment]
Indeed, it is sufficient to clear only the SID entry. Implementation was changed accordingly, therefore the issue can be closed.
