### ISSUE TITLE
Shadowing of Static Variable

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw#17]
This point was first brought up by ESA when they did their static code analysis of the CORDET Framework code (see e-mail from Roland dated 11 October 2016).

Consider module `CrFwOutManager`. This module defines a module-wide static variable called `outManagerData`. Several functions within this module (e.g. function `OutManagerExecAction`) define a local variable which also has the name `outManagerData`. The local variable then shadows the module-wide static variable. We should rename the local variable to a name like: `outManagerDataLocal`.

A similar problem exists for module CrFwInManager where the module-wide static variable `inManagerData` is shadowed by local variables of the same name. The same correction as in module CrFwOutManager should be done in this module, too.

**Comment by oppm** [comment]
Has already been merged into master.
