### ISSUE TITLE
Unnecssary Write

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw#18]
This point was first brought up by ESA when they did their static code analysis of the CORDET Framework code (see e-mail from Roland dated 11 October 2016).

In function CrFwFindCmdRepKindIndex in module CrFwUtilities, an unnecessary write operation has been found: the statement: `pos_half = length/2;` has no effect because `pos_half` is updated in the while loop and, if the while loop is not executed, the value of `pos_half` is never used. This statement should therefore be removed.

**Comment by oppm** [comment]
Has already been merged into master.
