### ISSUE TITLE
Wrong Type in Call to malloc

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw#19]
This point was first brought up by ESA when they did their static code analysis of the CORDET Framework code (see e-mail from Roland dated 11 October 2016).

In function `CrFwPcktQueueInit` of module `CrFwPcktQueue`, the following statement is made:

`pcktQueue->pckt = malloc(size*sizeof(CrFwPckt_t*));`

This statement might be incorrect and the correct statement is probably:

`pcktQueue->pckt = malloc(size*sizeof(CrFwPckt_t));`

I assign the ticket to Marcel so that he may check this matter and update the code if needed.

**Comment by oppm** [comment]
Yes, it is wrong. I'll change it...

**Comment by cechticky** [comment]
I saw that you solved the issue. Thanks, I'd suggest that you also close it.

**Comment by oppm** [comment]
Someone needs to first merge the branch to the master branch.... And shouldn't the one close the issue who has opened it ?

**Comment by cechticky** [comment]
I think it should be Alessandro, he is the maintainer for the cordetfw.

**Comment by pasetti** [comment]
The problem has been fixed and the fix has been pulled into the master branch.
