### ISSUE TITLE
Implementation of Ready Check of (17,3)

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw#56]
The current implementation of the ready check of TC(17,3) is as follows:

```
CrFwBool_t CrPsTestOnBoardConnectionReadyCheck(FwSmDesc_t __attribute__((unused)) smDesc) 
{
  CrFwCmpData_t*   inData;
  CrFwInCmdData_t* inSpecificData;
  CrFwPckt_t       inPckt;

  /* Return 'command is ready' */

  printf("CrPsTestOnBoardConnectionReadyCheck()\n");

  /* Get in packet */
  inData          = (CrFwCmpData_t*)FwSmGetData(smDesc);
  inSpecificData  = (CrFwInCmdData_t*)inData->cmpSpecificData;
  inPckt          = inSpecificData->pckt;

  /* Send Request Verification Acceptance Successful out-going report */
  SendReqVerifAccSuccRep(inPckt);

  return 1; /* always True */
}
```
This implementation seems wrong to me. The Ready Check returns TRUE when a command is ready to be executed and it returns FALSE otherwise. The Ready Check of TC(17,3) is specified to always return TRUE (see table 13.3 in the PUS Extension Specification Document). Hence, the function shown above should simply return 1. As a matter of fact, the Ready Check of all PUS Extension commands will just be a dummy function which returns 1 and you can simply use the same dummy function for all commands.

The implementation above sends "Acceptance Success Report" from within the Ready Check. This, too, seems wrong to me: the management of the Acceptance Success/Failure Reports is done by the InLoader component (see figure 15.2 of the CORDET User Manual) and should therefore be handled by the CORDET infrastructure.

**Comment by reimers** [comment]
We agreed on the use of the dummy functions and empty actions: The functions which are declared to return always true or false and empty actions will be replaced in the configuration by the  dummy functions offered by the framework. Therefore the functions in the service modules should be deleted.

In the latest version we do not send Service 1 reports from within other service modules. They will be generated in module CrFwRepInCmdOutcome() by using the outcome of the actions.
