### ISSUE TITLE
Coding of Procedures Modelled in FW Profile Tool

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw#59]
Consider the procedure implementing the Start Action for TC(17,3). This procedure is modelled in the FW Profile Tool. 

The model of this procedure in the FW Profile Tool does not contain any implementation-level information (i.e. there are no names for the functions which implement the procedure actions and guards). Does this mean that the code implementing this procedure was entirely written manually?

**Comment by reimers** [comment]
Except the Create function all the other functions for the nodes and guards are written manually in this case.

**Comment by reimers** [comment]
We have checked the manually written code with the generated one and it matches.
