### ISSUE TITLE
Implementation of Service 1 OutComponents

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw#66]
I have looked at the implementation of a couple of service 1 OutComponents and I see that they contain one single function as in the following example:

```
void CrPsReqVerifProgFailUpdateAction(FwSmDesc_t smDesc)
{
  CRFW_UNUSED(smDesc); /* remove if smDesc is used in this function */
  /* Implement the action logic here: */

  /* Load the value of the report parameters */
  /* NOT USED: done in IfswUtilities function, which packs and finalizes out-going packet */

  return;
}
```
This definition seems somewhat pointless.... Also I do not understand the meaning of the last comment ("NOT USED: done in IfswUtilities function, which packs and finalizes out-going packet"). What exactly is means in this comment?

The service 1 reports are all defined in the same way in table 8.2 of the PUS Extension Specification Document. In particular, they all have default implementations for their checks (Enable Check, Ready Check and Repeat Check) and for their action (Update Action). Hence, I do not quite understand why we need to define the modules which are currently defined in `RequestVerification/OutCmp`.

The modules which define a command or report are intended as "containers" for the functions which implement the actions and checks the command or report. If a report uses only the default implementations for its actions and checks, then there is no need for the "container module".

Note that the framework already offers functions which can be used for default actions and checks. For instance, function `CrFwOutCmpDefEnableCheck` provides the default implementation of the enable check of an out-going report or function `CrFwSmEmptyAction` implements a function representing a state machine action which returns without doing anything. Hence, for the service 1 reports, all functions required to implement the reports should already be available.

**Comment by reimers** [comment]
All Update Actions of the Service 1 OutComponents are now using function `CrFwSmEmptyAction `and the needless files were removed (see new version in github).
