### ISSUE TITLE
Implementation of Else Branch in FW Profile Procedures

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw#81]
In the procedures built using the FW Profile, the control flows coming out of a decision node must be such that one control flow has a guard which returns TRUE (to avoid the procedure remaining stuck at a decision node). This conditions can be easily satisfied as follows:

- The control flows out of a decision node have an order (this can be displayed by pressing the "show control flow order" button
- The last control flow out of a decision node can be implemented to return 1 (i.e. as an "Else" branch)

For example, consider the decision node at the bottom of the following diagram:

![image](https://user-images.githubusercontent.com/15838404/31311857-7fde165a-abb5-11e7-90b2-c0375734cdee.png)

Here, the function implementing the guard on the control flow with the order equal to 3 can be implemented as a function which always returns 1. Note that, within the FW Profile tool, this can be done by implementing the control flow using the option "Run Code | Else Guard". The code generator of the tool will then generate the function which returns 1. In practice, this means that, if you have a decision node with N out-going control flows, you only need to define functions for (N-1) guards.

This approach has been used extensively in CHEOPS and I would recommend that it also be used for the PUS Extension.

**Comment by reimers** [comment]
The guard from DECISION2 to DECISION2 was changed to an else guard as recommended.
