### ISSUE TITLE
Duplication of Hk/Diag Commands

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw#85]
I notice that the InCmd directory for service 3 contains two versions of each command. Consider for instance the HkCreateCmd defined in table 9.2 of the PUS Extension Specification Document. As far as I can see, this command is mapped to modules CrPsHkCreateDiagStruct (for the (3,1) command) and CrPsHkCreateHkStruct (for the (3,2) command). I do not understand the reason for this duplication: the actions and checks associated to a (3,1) or (3,2) command are exactly the same; why do we need two different modules? Why can we not have one single module called CrPsHkCreateCmd to implement the specification of the HkCreateCmd component?

Does perhaps the problem lie with the CORDET Editor Code Generator? 

Since the modules CrPsHkCreateDiagStruct and CrPsHkCreateHkStruct represent commands with the same behaviour, I would expect them to have the same implementation. This, however, is not the case: comparison of the functions CrPsHkCreateHkStructStartAction and CrPsHkCreateDiagStructStartAction shows that the two commands - (3,1) and (3,2) - are implemented with two different Start Actions. What is the reason for this difference?

**Comment by reimers** [comment]
Yes indeed, the modules with the same behaviour can be implemented as one common module. We already changed the implementation accordingly, e.g. modules CrPsHkCreateDiagStruct and CrPsHkCreateHkStruct were merged to the single module CrPsHkCreateCmd.
