### ISSUE TITLE
Error in Specification of Start Action of Command HkCreateCmd

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw#87]
While reviewing the implementation of the HkCreateCmd, I noticed that there is an error in the specification of this component. Its Progress Action is defined as follows in table 9.2: "Add the definition of the new report to the RDL, set its enabled status to 'disabled', and set the action outcome to 'completed'". However, the procedure in figure 9.1 (Start Action of Command HkCreateCmd) already includes the definition of the RDL entry and the setting of the enable status to Enable in node N5. I have therefore removed node N5 from procedure.

I assign the ticket to Christian so that he may transpose the change in the specification into the implementation (the action which was previously done in node N5 of the Start Action procedure must be moved to the Progress Action of HkCreateCmd).

**Comment by reimers** [comment]
The logic of node N5 is moved completely to the progress action of the HkCreateCmd according to the new specification.
