### ISSUE TITLE
Creation of Command and Report Procedures

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw#88]
Most commands and some reports use procedures to implement some of their actions and checks. At present, these procedures are created in function CrPsInitApp. This solution does not seem good to me because it puts the creation of procedures for all services in the same place and this would not be appropriate for users who only wish to support some services. A better solution might be to have, for each service, an "initialization module" which provides:

(a) An initialization function which creates the procedures needed for that service and
(b) The getter function to access the procedures

**Comment by reimers** [comment]
ad (a) 
The initialization function is now split and made available initialization functions for distinct services. The common initialization module has been deleted.

ad (b) 
Instead of using global variables new getter functions are implemented to access the procedures and state machines.
