### ISSUE TITLE
Parameterization of RDL Types

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw#89]
The RDL appears to be defined in module CrPsDpHk. Here, I find definitions such as:

  uint16_t sid[HK_N_REP_DEF];

It is certainly true that the sid is often defined as an unsigned integer of 16 bits but this type is not mandated by the PUS Standard. Hence, we should a typedef for this and other RDL variables and the typedef's should be defined in a header file such as CrPsUserConstant where user can customize them for their specific needs.

**Comment by reimers** [comment]
We already introduced specific data types, e.g. <pre>CrPsSid_t sid[HK_N_REP_DEF]</pre> which can be introduced by the user via typedef in CrPsUserConstants.h like <pre>typedef uint8_t CrPsSid_t;</pre>
