### ISSUE TITLE
Default Actions and Checks

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw#92]
A command or report is defined through its actions and checks. In most cases, default values for these actions and checks are used. In these cases, there is no need to define functions which implement these actions and checks because one can use the default implementations provided by the CORDET Framework.

Possibly, this problem might be due to the CORDET Editor which is not yet capable of distinguishing between default and non-default implementations of an action/check. This deficiency is covered by issue 20 in the Corder-Editor project and will be fixed in due course but, for the time being, the command and report definitions should be manually edited to remove all unnecessary functions. In my view. we must aim at an implementation which is as simple and streamlined as possible.

**Comment by reimers** [comment]
Already done. For all actions and checks of commands and reports using default values no functions are defined anymore. Therefore default functions are used in the corresponding lists in the CrFwInFacoryUserPar.h and CrFwOutFactoryUserPar.h.
