### ISSUE TITLE
Discriminating Between (3,25) and (3,26) in CrPsCmd3s1StartN2

### ISSUE THREAD

**Issue by pasetti** [pnp-software/cordetfw#93]
Function CrPsCmd3s1StartN2 contains the following TODO:

` /* TODO: TBD how to decide if it is a report of type (3,25) or (3,26) */`

The answer to the question posed in the TODO is that a (3,25) is generated in response to a (3,1) and a (3,26) is generated in response to a (3,2).

**Comment by reimers** [comment]
Done, can be closed.
