### ISSUE TITLE
HkOneShotCmd triggers periodic HK reports

### ISSUE THREAD

**Issue by reimers** [pnp-software/cordetfw#99]
The OneShotCmd sets the enable flag in the data pool to "enabled". If the HK report is loaded in the OuLoader it will start sending HK reports. But the "Ready Check" increments the cycleCnt and ckecks if its equal to the period and therefore does not stop sending HK reports afterwards. 

One solution could be to set the period to zero but then we override the preset value of the period. Maybe we could restore to the preset values of the period somewhere. Or we introduce a new data pool flag for triggering a one shot report.

**Comment by pasetti** [comment]
Yes, I agree with Christian's analysis but I do not see the behaviour he describes as a problem. My reasoning is that the ground should only send the HkOneShotCmd to reports which have been defined with a period equal to zero (i.e. to reports which have been defined as "one-shot reports"). In such a case, the behaviour of our framework is exactly as expected.

If the ground sends the HkOneShotCmd to a report which has been defined with a non-zero period (i.e. to a report which is intended to be generated as a cyclical report), then the resulting behaviour is that the report is enabled and is generated once immediately and then periodically with its associated period. To my mind, this behaviour is reasonable.

In fact, there might be an actual use case for sending the  HkOneShotCmd command to a period report. Consider the following scenario:

- Report R is defined to have a period P which is very long (say, once per hour)
- The ground wishes to have an instance of R without however changing its period
- The ground sends HkOneShotCmd for report R at time t. This results in one instance of report R being generated at time t (the next one will be generated at t+P, t+2P, etc)

Hence, I would say that all is as it should be ...
